Add functionalities to get,update, delete facility by id (user)
cwwojin/FORK_backend pull request #20
Opened 2024-05-20 12:47 UTC by nurgissas

## What was added
- Add get, update, delete facility by user id methods to userServices
- Corresponding to the above methods changes in controller, router

## Related Issues
- Didn't run unit test with existing facility id 
- But run negative unit tests to endpoints targetting above methods

## Future Works
- Admin facility registration request, search engine to map services

## Checklist
- [ ] I have performed unit tests
- [ ] I have added necessary docs
- [ ] I have checked for potential bugs & issues

2024-05-21 15:40 UTC, cwwojin commented
Great work!
1. `POST /api/facilities/facility-requests` - the `content` should have required field `address` and optional fields `openingHours, menu, preferences, stampRuleset, stampRewards` that include all data to be inserted. validate fields accordingly
2. `GET /api/admin/facility-requests` - OK, but adding optional query parameters `authorId, status` would be nice
3. `GET /api/admin/facility-requests/:id` - OK
4. `POST /api/admin/facility-requests/:id/accept` - insert `preferences, stampRuleset, stampRewards` also
5. `POST /api/admin/facility-requests/:id/decline` - OK
6. `DELETE /api/admin/facility-requests/:id` - OK

Also, you don't need to update `updated_at = now()` -> this will be done by DB

2024-05-21 15:42 UTC, cwwojin requested changes

2024-05-21 15:42 UTC, cwwojin commented on myapp/src/services/adminService.js
> +    const data = JSON.parse(request.content);
This will give error if the `content` is an object and not JSONstring

2024-05-22 13:13 UTC, cwwojin requested changes

2024-05-22 13:13 UTC, cwwojin commented on myapp/src/services/adminService.js
> +
Here, also insert the facility-manager relationship
`"insert into manages (user_id, facility_id) values ($1, $2)", [request.author_id, facility.id]`

2024-05-22 13:13 UTC, cwwojin commented on myapp/src/services/facilityService.js
> +    const status = await this.getFacilityRegistrationStatus(facility.authorId);
This check will not allow facility update, if the facility is either
- made by admin without the request process, or any facilities that are pre-existent in DB
- request is deleted after being accepted

2024-05-23 13:51 UTC, nurgissas commented
POST /api/facilities/facility-requests:
- Added optional fields: address, openingHours, menu, preferences, stampRuleset, stampRewards.
- Validated as objects or arrays.
- Content is treated as object, not string

GET /api/admin/facility-requests:
- Added optional query parameters: authorId, status.

POST /api/admin/facility-requests/:id/accept:
- Added insertion for preferences, stampRuleset, stampRewards.

2024-05-23 16:19 UTC, cwwojin commented
@nurgissas 
My changes :

1. `GET /api/admin/facility-requests` change query parameter name to `authorId -> user` (for consistency with other method)
2. Edit format of `content` in facility request : `stampRuleset: { totalCnt: 10, rewards: []}`
    stampRuleset.rewards is the array with rewards -> to use `facilityService.createStampRuleset` for inserting all
1. Change most fields that use `notEmpty() -> exists().isString()` except for `businessId` Also, allow facility URL and email to be empty string

2024-05-23 16:20 UTC, cwwojin commented
Great Work ! I will merge this after solving conflict with dev branch

2024-05-23 17:21 UTC, cwwojin approved these changes

2024-05-23 17:21 UTC, merged